### ISSUE TITLE
CSS Styling - Approve Membership Buttons

### ISSUE THREAD

**Issue by tevers200** [brainthee/CHAOTICA#53]
The buttons for notification requests to approve/reject organisational membership are hard to read in dark mode
![image](https://github.com/brainthee/CHAOTICA/assets/4094504/8b5b0cac-d7a4-4d3e-ad61-ae01d094fd72)

Applying either the `text-dark` or `text-light` CSS property to the button elements in dark mode makes readability somewhat better.

**Comment by brainthee** [comment]
Ahh I see why. Left over's from the theme I used super early in development :) All sorted. Will reach main shortly! Will also work on some user management improvements too!
