### ISSUE TITLE
[Bug] Add a Job Function Fails

### ISSUE THREAD

**Issue by tevers200** [brainthee/CHAOTICA#62]
When adding a new job, the POST request fails to create the job in the latest version (worked fine in previous releases).

"POST /job/create/ HTTP/1.1" 200 53592
![image](https://github.com/brainthee/CHAOTICA/assets/4094504/82f758b5-f096-4ff3-9d83-91c07c89cf42)

Hitting the "Save" button sends a POST request to /job/create, but then reloads the page as it was prior to submission.

**Comment by brainthee** [comment]
Well that was a fun puzzle! Turns out it was failing due to form validation checks. Which wasn't being displayed!

it's failing out on this:
```
created_by
This field is required.
```

**Comment by brainthee** [comment]
So because created_by isn't shown in the form (since it's not a user-controlled field) - it's not rendered out!

**Comment by brainthee** [comment]
Turns out it was due to some dynamic field locking I added a few commits ago. Added the relevant fields to `excluded` for both jobs and phases (it affected phases too)
